"""initial schema

Revision ID: 1479f57b36fb
Revises: 
Create Date: 2026-04-10 12:02:09.371740

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1479f57b36fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_site_id'), 'data_sources', ['site_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_site_id'), 'ingestion_jobs', ['site_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_site_id'), 'interventions', ['site_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('inaturalist', 'usgs_bio', 'manual_csv', 'manual_pdf', name='observation_source_type'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taxon_name', sa.String(length=255), nullable=True),
    sa.Column('taxon_id', sa.Integer(), nullable=True),
    sa.Column('taxon_rank', sa.String(length=50), nullable=True),
    sa.Column('iconic_taxon', sa.String(length=50), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('quality_grade', sa.String(length=50), nullable=True),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_site_observed', 'observations', ['site_id', 'observed_at'], unique=False)
    op.create_index('ix_obs_site_source', 'observations', ['site_id', 'source_type'], unique=False)
    op.create_index('ix_obs_site_taxon', 'observations', ['site_id', 'taxon_name'], unique=False)
    op.create_index('ix_obs_source_id', 'observations', ['source_type', 'source_id'], unique=True)
    op.create_index(op.f('ix_observations_site_id'), 'observations', ['site_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('watershed', sa.String(length=100), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('huc12_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restoration_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indicator_species', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('invasive_watchlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_watershed'), 'sites', ['watershed'], unique=False)
    op.create_table('time_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('usgs', 'owdp', 'manual_csv', name='timeseries_source_type'), nullable=False),
    sa.Column('quality_flag', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_series_site_id'), 'time_series', ['site_id'], unique=False)
    op.create_index('ix_ts_site_station_param_time', 'time_series', ['site_id', 'station_id', 'parameter', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ts_site_station_param_time', table_name='time_series')
    op.drop_index(op.f('ix_time_series_site_id'), table_name='time_series')
    op.drop_table('time_series')
    op.drop_index(op.f('ix_sites_watershed'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_observations_site_id'), table_name='observations')
    op.drop_index('ix_obs_source_id', table_name='observations')
    op.drop_index('ix_obs_site_taxon', table_name='observations')
    op.drop_index('ix_obs_site_source', table_name='observations')
    op.drop_index('ix_obs_site_observed', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_interventions_site_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_ingestion_jobs_site_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_data_sources_site_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
