"""add geology tables

Revision ID: 3047ecff11e2
Revises: b128c1540c58
Create Date: 2026-04-11 15:37:30.347371

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3047ecff11e2'
down_revision: Union[str, Sequence[str], None] = 'b128c1540c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_time_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geologic_unit_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('reading_level', sa.String(length=50), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('evidence_cited', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_time_stories_geologic_unit_id'), 'deep_time_stories', ['geologic_unit_id'], unique=False)
    op.create_index('ix_deep_time_unit_level', 'deep_time_stories', ['geologic_unit_id', 'reading_level'], unique=True)
    op.create_table('fossil_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('taxon_name', sa.String(length=255), nullable=True),
    sa.Column('taxon_id', sa.String(length=100), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('phylum', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('order_name', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('age_min_ma', sa.Float(), nullable=True),
    sa.Column('age_max_ma', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('formation', sa.String(length=255), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('collector', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('museum', sa.String(length=255), nullable=True),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST index on location created automatically by GeoAlchemy2
    op.create_index(op.f('ix_fossil_occurrences_period'), 'fossil_occurrences', ['period'], unique=False)
    op.create_index(op.f('ix_fossil_occurrences_taxon_name'), 'fossil_occurrences', ['taxon_name'], unique=False)
    op.create_index('ix_fossil_source_id', 'fossil_occurrences', ['source', 'source_id'], unique=True)
    op.create_table('geologic_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('unit_name', sa.String(length=255), nullable=True),
    sa.Column('formation', sa.String(length=255), nullable=True),
    sa.Column('rock_type', sa.String(length=100), nullable=True),
    sa.Column('lithology', sa.String(length=255), nullable=True),
    sa.Column('age_min_ma', sa.Float(), nullable=True),
    sa.Column('age_max_ma', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST index on geometry created automatically by GeoAlchemy2
    op.create_index(op.f('ix_geologic_units_formation'), 'geologic_units', ['formation'], unique=False)
    op.create_index(op.f('ix_geologic_units_period'), 'geologic_units', ['period'], unique=False)
    op.create_index('ix_geologic_units_source_id', 'geologic_units', ['source', 'source_id'], unique=False)
    op.create_table('land_ownership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('agency', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('admin_unit', sa.String(length=255), nullable=True),
    sa.Column('collecting_status', sa.String(length=50), nullable=True),
    sa.Column('collecting_rules', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST index on geometry created automatically by GeoAlchemy2
    op.create_index(op.f('ix_land_ownership_agency'), 'land_ownership', ['agency'], unique=False)
    op.create_index(op.f('ix_land_ownership_collecting_status'), 'land_ownership', ['collecting_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_ownership_collecting_status'), table_name='land_ownership')
    op.drop_index(op.f('ix_land_ownership_agency'), table_name='land_ownership')
    op.drop_table('land_ownership')
    op.drop_index('ix_geologic_units_source_id', table_name='geologic_units')
    op.drop_index(op.f('ix_geologic_units_period'), table_name='geologic_units')
    op.drop_index(op.f('ix_geologic_units_formation'), table_name='geologic_units')
    op.drop_table('geologic_units')
    op.drop_index('ix_fossil_source_id', table_name='fossil_occurrences')
    op.drop_index(op.f('ix_fossil_occurrences_taxon_name'), table_name='fossil_occurrences')
    op.drop_index(op.f('ix_fossil_occurrences_period'), table_name='fossil_occurrences')
    op.drop_table('fossil_occurrences')
    op.drop_index('ix_deep_time_unit_level', table_name='deep_time_stories')
    op.drop_index(op.f('ix_deep_time_stories_geologic_unit_id'), table_name='deep_time_stories')
    op.drop_table('deep_time_stories')
    # ### end Alembic commands ###
