"""sync models with actual database

Revision ID: b128c1540c58
Revises: medallion_001
Create Date: 2026-04-11 05:48:32.651324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b128c1540c58'
down_revision: Union[str, Sequence[str], None] = 'medallion_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fire_perimeters', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_fire_site'), table_name='fire_perimeters')
    op.drop_index(op.f('ix_fire_year'), table_name='fire_perimeters')
    op.create_index('idx_fire_perimeters_perimeter', 'fire_perimeters', ['perimeter'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fire_perimeters_site_id'), 'fire_perimeters', ['site_id'], unique=False)
    op.alter_column('impaired_waters', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_impaired_site'), table_name='impaired_waters')
    op.create_index('idx_impaired_waters_geometry', 'impaired_waters', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_impaired_waters_site_id'), 'impaired_waters', ['site_id'], unique=False)
    op.alter_column('stream_flowlines', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_flowline_name'), table_name='stream_flowlines')
    op.drop_index(op.f('ix_flowline_site'), table_name='stream_flowlines')
    op.create_index('idx_stream_flowlines_flowline', 'stream_flowlines', ['flowline'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_stream_flowlines_gnis_name'), 'stream_flowlines', ['gnis_name'], unique=False)
    op.create_index(op.f('ix_stream_flowlines_site_id'), 'stream_flowlines', ['site_id'], unique=False)
    op.alter_column('watershed_boundaries', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_wbd_huc'), table_name='watershed_boundaries')
    op.drop_index(op.f('ix_wbd_site'), table_name='watershed_boundaries')
    op.create_index('idx_watershed_boundaries_geometry', 'watershed_boundaries', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_watershed_boundaries_huc12'), 'watershed_boundaries', ['huc12'], unique=False)
    op.create_index(op.f('ix_watershed_boundaries_site_id'), 'watershed_boundaries', ['site_id'], unique=False)
    op.alter_column('wetlands', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_wetland_site'), table_name='wetlands')
    op.create_index('idx_wetlands_geometry', 'wetlands', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_wetlands_site_id'), 'wetlands', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wetlands_site_id'), table_name='wetlands')
    op.drop_index('idx_wetlands_geometry', table_name='wetlands', postgresql_using='gist')
    op.create_index(op.f('ix_wetland_site'), 'wetlands', ['site_id'], unique=False)
    op.alter_column('wetlands', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_watershed_boundaries_site_id'), table_name='watershed_boundaries')
    op.drop_index(op.f('ix_watershed_boundaries_huc12'), table_name='watershed_boundaries')
    op.drop_index('idx_watershed_boundaries_geometry', table_name='watershed_boundaries', postgresql_using='gist')
    op.create_index(op.f('ix_wbd_site'), 'watershed_boundaries', ['site_id'], unique=False)
    op.create_index(op.f('ix_wbd_huc'), 'watershed_boundaries', ['huc12'], unique=False)
    op.alter_column('watershed_boundaries', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_stream_flowlines_site_id'), table_name='stream_flowlines')
    op.drop_index(op.f('ix_stream_flowlines_gnis_name'), table_name='stream_flowlines')
    op.drop_index('idx_stream_flowlines_flowline', table_name='stream_flowlines', postgresql_using='gist')
    op.create_index(op.f('ix_flowline_site'), 'stream_flowlines', ['site_id'], unique=False)
    op.create_index(op.f('ix_flowline_name'), 'stream_flowlines', ['gnis_name'], unique=False)
    op.alter_column('stream_flowlines', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_impaired_waters_site_id'), table_name='impaired_waters')
    op.drop_index('idx_impaired_waters_geometry', table_name='impaired_waters', postgresql_using='gist')
    op.create_index(op.f('ix_impaired_site'), 'impaired_waters', ['site_id'], unique=False)
    op.alter_column('impaired_waters', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_fire_perimeters_site_id'), table_name='fire_perimeters')
    op.drop_index('idx_fire_perimeters_perimeter', table_name='fire_perimeters', postgresql_using='gist')
    op.create_index(op.f('ix_fire_year'), 'fire_perimeters', ['fire_year'], unique=False)
    op.create_index(op.f('ix_fire_site'), 'fire_perimeters', ['site_id'], unique=False)
    op.alter_column('fire_perimeters', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
