"""add mineral_deposits table

Revision ID: cbeab57c94e5
Revises: 3047ecff11e2
Create Date: 2026-04-11 16:36:46.907303

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbeab57c94e5'
down_revision: Union[str, Sequence[str], None] = '3047ecff11e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mineral_deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('dev_status', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST index on location created automatically by GeoAlchemy2
    op.create_index(op.f('ix_mineral_deposits_commodity'), 'mineral_deposits', ['commodity'], unique=False)
    op.create_index('ix_mineral_source_id', 'mineral_deposits', ['source', 'source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mineral_source_id', table_name='mineral_deposits')
    op.drop_index(op.f('ix_mineral_deposits_commodity'), table_name='mineral_deposits')
    op.drop_table('mineral_deposits')
    # ### end Alembic commands ###
